### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by kuriel-dev** [GLINCKER/glin-profanity#29]
export { Filter } from './filters/Filter';

**Comment by thegdsks** [comment]
## Issue #29 - SyntaxError: Unexpected token 'export'

Hi there,

Thank you so much for using **Glin-Profanity** and for bringing this issue to our attention. We’ve just released an update in version **1.1.8**, and this issue with the `export { Filter }` causing a `SyntaxError` has now been resolved.

Let us know if you encounter any further issues.

Thanks again for your support!

Best regards,  
The Glincker Team
